{% set name = "ttopt" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ttopt-{{ version }}.tar.gz
  sha256: 2e66ba0919660dbdd44a7912350ae6d28db474537b63b45374e4a5e2736642e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - maxvolpy

test:
  imports:
    - ttopt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AndreiChertkov/ttopt
  summary: Multivariate function minimizer based on the tensor train approach.
  dev_url: https://github.com/AndreiChertkov/ttopt
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
